Repository ho0ber/NK2Tray, pull requests merged in 2019-10, with the labels that each got.

#29 refactored to keep the settings after crashing
  NK2Tray/ConfigSaver.cs
  NK2Tray/MidiDevice.cs
  NK2Tray/NK2Tray.csproj
Labels: bug

#31 catch exception that leads to crash
  NK2Tray/MixerSession.cs
Labels: bug

#35 Improved finding mixer sessions for process ID's
  NK2Tray/AudioDevice.cs
  NK2Tray/Fader.cs
  NK2Tray/MixerSession.cs
Labels: bug, enhancement

#30 Focus slider
  NK2Tray/MidiDevice.cs
  NK2Tray/MixerSession.cs
  NK2Tray/Program.cs
Labels: enhancement
